### PR TITLE
Owner alias plugin

### LINKED ISSUE #10: Use of owner-alias field for owners field in Outscale builders
_This issue was originally opened by @skelkey as hashicorp/packer#10052. It was migrated here as a result of the [Packer plugin split](https://github.com/hashicorp/packer/issues/8610#issuecomment-770034737). The original body of the issue is below._

<hr>

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

It's not possible to filter image by owner-alias instead of owner-id. When I'm searching for an image, I would filter on Outscale account by using it's owner alias. (cc @Hakujou)

The list of owner-id could mix owner-id and owner-alias to filter the list of image.

#### Use Case(s)

Select the latest Outscale official image instead of fixing it by its id.

### PR DESCRIPTION
**Pull request by outscale-mgo**
Note that I didn't test it with new plugin system, but only with old packer repository. 
Closes #10

### CODE REVIEW

**Comment by marinsalinas** [comment]
@SwampDragons is there any new way to test the new changes over the builers?

**Comment by sylviamoss** [comment]
@marinsalinas Yes. If you run `make dev`, the plugin will be installed under `~/.packer.d/plugins/` as `packer-plugin-outscale`. Any Packer from v1.7.0 should be able to discover the plugin and use it instead of the built-in one. 🤔

**Review by sylviamoss — APPROVED** [review]

**Comment by azr** [comment]
You can also run `go build . &&  packer run test.pkr.hcl`, Packer will discover the plugin if it is in the cwd

**Comment by SwampDragons** [comment]
Have we started the partner conversation about transferring ownership of this repo to Outscale so you don't need to wait on our merge approval?

**Comment by Hakujou** [comment]
@SwampDragons I don't think so.

With this separate repo and the possibility of Outscale being owner of it, would osc builders still part of the main Packer binary, or would it be more like Terraform (separate binary, and possibly a repository) ?

**Comment by sylviamoss** [comment]
@Hakujou Currently the osc builders are being vedored in Packer [here](https://github.com/hashicorp/packer/blob/master/command/vendored_plugins.go#L41) and all of its code now is in this repository and should remain in it. In the near future plugins won't be vondered anymore and the binaries will have to be downloaded with `packer init` + `required_plugins` block.  So yeah, since breakout this plugin now has a separate binary and repository.

**Comment by outscale-mgo** [comment]
> You can also run `go build . && packer run test.pkr.hcl`, Packer will discover the plugin if it is in the cwd

Thanks, Just test that on my machine, it work.

**Comment by SwampDragons** [comment]
To expand on what Moss said, the binary will be separate, but installation will happen seamlessly via the init command and a "packer" block in the config file. Documentation will remain on the Packer.io website, with a "partner" tag to show that it is being maintained by someone in a partner relationship with HashiCorp.

**Comment by Hakujou** [comment]
@sylviamoss @SwampDragons Ok, thanks a lot. I'll need to discuss it with other Outscale employees as it's not a kind of decision I can take alone.
Once we have figured this out, should we apply through Hashicorp Tech Partner page (https://www.hashicorp.com/go/tech-partner), or should I reach @SwampDragons  directly by mp ?

Until then, this MR has been tested and is working, it can be merged :)

**Comment by sylviamoss** [comment]
Thanks, @Hakujou. I'll let @SwampDragons give you the information on which is the best channel for you to reach out to.

**Pull request merged**
