### PR TITLE
add test plugin example

### PR DESCRIPTION
**Pull request by outscale-hmi**
Signed-off-by: Ubuntu <outscale@ip-10-9-54-115.eu-west-2.compute.internal>

**DELETE THIS TEMPLATE BEFORE SUBMITTING**

In order to have a good experience with our community, we recommend that you
read the contributing guidelines for making a PR, and understand the lifecycle
of a Packer Plugin PR:

https://github.com/hashicorp/packer-plugin-outscale/blob/main/.github/CONTRIBUTING.md#opening-an-pull-request

Describe the change you are making here!

Please include tests. We recommend looking at existing tests as an example. 

If your PR resolves any open issue(s), please indicate them like this so they will be closed when your PR is merged:

Closes #xxx
Closes #xxx

### CODE REVIEW

**Review by sylviamoss — APPROVED** [review]
Thanks! LGTM 👍🏼  Need you to sign the CLA so that we can merge it.

**Comment by outscale-hmi** [comment]
> Thanks! LGTM 👍🏼 Need you to sign the CLA so that we can merge it.

Thanks, I already signed but still pending I think.

**Comment by azr** [comment]
@outscale-hmi, the email used in the commits needs to be the email used for the CLA signing, otherwise, the bot cannot match you :)

**Comment by outscale-hmi** [comment]
> @outscale-hmi, the email used in the commits needs to be the email used for the CLA signing, otherwise, the bot cannot match you :)

I am unable to modify the form, how can I reset the informations filled before ?

**Comment by sylviamoss** [comment]
You can amend your commit and add the correct e-mail address with
```
git commit --amend --author="Your Name <email@address.com>"
```
I this should work

**Comment by outscale-hmi** [comment]
> You can amend your commit and add the correct e-mail address with
> 
> ```
> git commit --amend --author="Your Name <email@address.com>"
> ```
> 
> I this should work

It is okey now!

**Review by azr — APPROVED** [review]
LGTM !

**Pull request merged**
